### ISSUE TITLE
Database Encoding do not Support UTF8

### ISSUE THREAD

**Issue by SongRb** [awonderfullife/Electronic-book-share-platform#12]
Trying to insert a utf8 string into database, got following error:  
~~~~Traceback (most recent call last):
  File "D:/Study/Software Engineering/Group Project/Electronic-book-share-platform/data_base_test.py", line 7, in <module>
    ms.add_user(u'2333',u'你好',u'233')
  File "D:\Study\Software Engineering\Group Project\Electronic-book-share-platform\dataBaseSupport.py", line 54, in add_user
    self.ExecNonQuery(s)
  File "D:\Study\Software Engineering\Group Project\Electronic-book-share-platform\dataBaseSupport.py", line 46, in ExecNonQuery
    cur.execute(sql)
  File "pymssql.pyx", line 447, in pymssql.Cursor.execute (pymssql.c:7119)
  File "_mssql.pyx", line 1011, in _mssql.MSSQLConnection.execute_query (_mssql.c:11586)
  File "_mssql.pyx", line 1042, in _mssql.MSSQLConnection.execute_query (_mssql.c:11466)
  File "_mssql.pyx", line 1162, in _mssql.MSSQLConnection.format_and_run_query (_mssql.c:12632)
  File "_mssql.pyx", line 200, in _mssql.ensure_bytes (_mssql.c:2702)
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 115-116: ordinal not in range(128)
~~~~

**Comment by awonderfullife** [comment]
just see this:   
In app.py:  
![image](https://user-images.githubusercontent.com/18577265/27247941-3cae7bfa-5330-11e7-892c-2c3e9221c3ea.png)



output:  
![image](https://user-images.githubusercontent.com/18577265/27247944-48b56c60-5330-11e7-8dd7-b529be758cfd.png)

I succeed by this~
